FROM golang:1.23 AS build
WORKDIR /src
COPY . .
RUN CGO_ENABLED=0 go build -o /out/virtualpcd ./cmd/virtualpcd
FROM gcr.io/distroless/static-debian12
COPY --from=build /out/virtualpcd /virtualpcd
ENTRYPOINT ["/virtualpcd"]
